### ISSUE TITLE
MC 1.21.4 support - WorldEdit issues & mc-assets version gap

### ISSUE THREAD

**Issue by xdLawless2** [mc-bench/mc-bench-backend#182]
Hey yall I was setting up mcbench locally with mc version 1.21.4 and ran into a couple of issues. I had CC help me dig through the codebase and figure out what was going wrong, thought I'd share what we found

1. WorldEdit doesn't work on Paper 1.21.4
WorldEdit 7.3.x throws a `NoClassDefFoundError` for some Actor class when it tries to load. Tried a few different versions but couldn't get it working. CC ended up switching to FastAsyncWorldEdit (FAWE) 2.14.4 which works fine, but that means the schematic path changes from `/data/plugins/WorldEdit/schematics` to `/data/plugins/FastAsyncWorldEdit/schematics` which then needs to patched in `run.py`.

2. mc-assets doesn't have 1.21.4
The render-worker crashed because `mc-assets==1.13.0rc0` only goes up to 1.21.1. Got this error:
minecraft_assets.MinecraftVersionError: Minecraft version '1.21.4' not found in assets

for now I just added a fallback in `ResourceLoader` to use 1.21.1 assets when 1.21.4 is requested. This works fine since the block assets are pretty much the same.

We could use an env variable to let the user chose between WorldEdit or FAWE, and update the mc-assets package to pull in 1.21.4 from upstream PrismarineJS (they already have it). I could make Pr's for any of these, just lmk if this seems right.
